import type {
  ActivityEntry,
  Control,
  Engagement,
  EvidenceRequest,
  Stakeholder,
} from "./types";

/** Frozen "today" so the seeded overdue/due-soon states stay stable in the prototype. */
export const TODAY = new Date("2026-07-29T09:00:00Z");

export const engagement: Engagement = {
  id: "eng_001",
  name: "SOC 2 Type II, FY26",
  client_name: "Northwind Logistics, Inc.",
  industry: null,
  company_size: null,
  description: null,
  frameworks: ["SOC2"],
  period_start: "2025-07-01",
  period_end: "2026-06-30",
  lead_auditor: "A. Rao",
};

export const controls: Control[] = [
  { id: "c1", ref: "CC6.1", category: "Logical Access", title: "Logical access security measures" },
  { id: "c2", ref: "CC6.2", category: "Logical Access", title: "User registration and authorization" },
  { id: "c3", ref: "CC6.3", category: "Logical Access", title: "Access removal and modification" },
  { id: "c4", ref: "CC7.2", category: "System Operations", title: "Monitoring for anomalies" },
  { id: "c5", ref: "CC7.3", category: "System Operations", title: "Security incident evaluation" },
  { id: "c6", ref: "CC8.1", category: "Change Management", title: "Change authorization and testing" },
  { id: "c7", ref: "CC9.2", category: "Risk Mitigation", title: "Vendor and business partner risk" },
  { id: "c8", ref: "A1.2", category: "Availability", title: "Backup and recovery procedures" },
  { id: "c9", ref: "CC1.4", category: "Control Environment", title: "Personnel competence and training" },
  { id: "c10", ref: "CC2.2", category: "Communication", title: "Internal security communication" },
];

export const stakeholders: Stakeholder[] = [
  { id: "s1", full_name: "Marcus Webb", email: "m.webb@northwind.example", role_title: "IT Manager" },
  { id: "s2", full_name: "Priya Nandakumar", email: "p.nanda@northwind.example", role_title: "DevOps Lead" },
  { id: "s3", full_name: "Dana Whitfield", email: "d.whitfield@northwind.example", role_title: "Head of People Ops" },
  { id: "s4", full_name: "Tomas Lindqvist", email: "t.lindqvist@northwind.example", role_title: "Security Engineer" },
  { id: "s5", full_name: "Grace Ofori", email: "g.ofori@northwind.example", role_title: "Procurement Manager" },
];

export const stakeholderById = Object.fromEntries(
  stakeholders.map((s) => [s.id, s]),
) as Record<string, Stakeholder>;

export const controlByRef = Object.fromEntries(
  controls.map((c) => [c.ref, c]),
) as Record<string, Control>;

export const evidenceRequests: EvidenceRequest[] = [
  {
    id: "req_014",
    engagement_id: "eng_001",
    control_ref: "CC6.2",
    title: "Q2 user access review: production AWS accounts",
    description:
      "Export of the quarterly access review for all production AWS accounts, including reviewer sign-off and any revocations actioned.",
    stakeholder_id: "s1",
    status: "pending_review",
    due_date: "2026-07-24",
    sent_at: "2026-07-10T14:02:00Z",
    reminder_count: 1,
    last_activity_at: "2026-07-28T16:41:00Z",
    files: [
      {
        id: "f_101",
        filename: "Q2-2026-AWS-access-review.pdf",
        mime_type: "application/pdf",
        size_bytes: 412_800,
        page_count: 6,
        uploaded_at: "2026-07-28T16:38:00Z",
        uploaded_by_stakeholder_id: "s1",
      },
      {
        id: "f_102",
        filename: "iam-users-export-2026-06-30.csv",
        mime_type: "text/csv",
        size_bytes: 88_400,
        page_count: null,
        uploaded_at: "2026-07-28T16:40:00Z",
        uploaded_by_stakeholder_id: "s1",
      },
    ],
    ai_review: {
      id: "air_101",
      evidence_file_id: "f_101",
      model: "gpt-4.1",
      reviewed_at: "2026-07-28T16:41:00Z",
      doc_type: "Access Review Export",
      doc_type_alternatives: ["User Entitlement Report", "IAM Configuration Export"],
      summary:
        "A six-page quarterly user access review covering 4 production AWS accounts and 118 IAM principals, dated 30 June 2026. Each account lists the reviewer, review date, and per-user disposition (retain / revoke). 7 users are marked for revocation. The document is signed by the IT Manager on p.6 but contains no second-level approver signature, and the revocation actions are listed as pending rather than evidenced as completed.",
      completeness: "partial",
      suggested_control_refs: ["CC6.2", "CC6.3"],
      flags: [
        {
          id: "fl_1",
          severity: "blocker",
          title: "Revocations not evidenced as completed",
          detail:
            "7 users are marked 'revoke, pending'. No ticket IDs, timestamps, or confirmation export show the removals were actually performed. Testing operating effectiveness for CC6.3 requires completion evidence.",
          location: "p.4 §3 (Disposition table)",
        },
        {
          id: "fl_2",
          severity: "warning",
          title: "Missing second-level approval",
          detail:
            "The access review procedure referenced on p.1 requires sign-off by both the system owner and the security function. Only the IT Manager signature is present.",
          location: "p.6 (Sign-off block)",
        },
        {
          id: "fl_3",
          severity: "warning",
          title: "Review period does not cover full quarter",
          detail:
            "Header states the review covers 15 Apr to 30 Jun 2026. The first two weeks of the quarter (1 to 14 Apr) are not covered by this or any other submitted evidence.",
          location: "p.1 (Header)",
        },
        {
          id: "fl_4",
          severity: "info",
          title: "Possible duplicate of REQ-009",
          detail:
            "The attached CSV export shares a filename pattern and row count with the file submitted under REQ-009 (Q1 access review). Confirm the correct period was exported.",
          location: "iam-users-export-2026-06-30.csv",
        },
      ],
      excerpts: [
        {
          location: "p.1",
          text: "Quarterly User Access Review: Production Environments. Review period: 15 Apr 2026 to 30 Jun 2026. Prepared by: M. Webb, IT Manager.",
        },
        {
          location: "p.4 §3",
          text: "j.calloway | Contractor | Last login 2026-02-11 | Disposition: REVOKE (pending)",
        },
        {
          location: "p.6",
          text: "Reviewed and approved: M. Webb, IT Manager, 30 Jun 2026. [Security sign-off: ____________ ]",
        },
      ],
    },
    decision: null,
  },
  {
    id: "req_011",
    engagement_id: "eng_001",
    control_ref: "CC8.1",
    title: "Change management tickets: sample of 25 production deploys",
    description:
      "Ticket records for a sample of 25 production changes showing approval, testing evidence, and deployment timestamp.",
    stakeholder_id: "s2",
    status: "pending_review",
    due_date: "2026-07-27",
    sent_at: "2026-07-13T09:15:00Z",
    reminder_count: 0,
    last_activity_at: "2026-07-27T11:20:00Z",
    files: [
      {
        id: "f_090",
        filename: "change-tickets-sample-25.xlsx",
        mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        size_bytes: 240_100,
        page_count: null,
        uploaded_at: "2026-07-27T11:18:00Z",
        uploaded_by_stakeholder_id: "s2",
      },
    ],
    ai_review: {
      id: "air_090",
      evidence_file_id: "f_090",
      model: "gpt-4.1",
      reviewed_at: "2026-07-27T11:20:00Z",
      doc_type: "Change Ticket Export",
      doc_type_alternatives: ["Deployment Log"],
      summary:
        "Spreadsheet export of 25 production change tickets between 1 Jul 2025 and 30 Jun 2026. Every row carries a requester, approver, and deploy timestamp. 23 of 25 rows reference a linked test run; 2 rows are emergency changes with retrospective approval recorded within 24 hours.",
      completeness: "complete",
      suggested_control_refs: ["CC8.1"],
      flags: [
        {
          id: "fl_5",
          severity: "info",
          title: "2 emergency changes with retrospective approval",
          detail:
            "CHG-4471 and CHG-4602 were approved after deployment. This is permitted by the client's policy but is typically tested as a separate population.",
          location: "Rows 12, 19",
        },
      ],
      excerpts: [
        {
          location: "Row 12",
          text: "CHG-4471 | Emergency hotfix: payment queue | Deployed 2026-02-03 22:14 | Approved 2026-02-04 08:02 by P. Nandakumar",
        },
      ],
    },
    decision: null,
  },
  {
    id: "req_007",
    engagement_id: "eng_001",
    control_ref: "CC6.3",
    title: "Termination checklist: all leavers in period",
    description: "Completed offboarding checklists evidencing access removal within 24 hours of termination.",
    stakeholder_id: "s3",
    status: "changes_requested",
    due_date: "2026-07-18",
    sent_at: "2026-07-02T10:00:00Z",
    reminder_count: 2,
    last_activity_at: "2026-07-26T09:12:00Z",
    files: [
      {
        id: "f_070",
        filename: "offboarding-checklists-FY26.pdf",
        mime_type: "application/pdf",
        size_bytes: 1_820_400,
        page_count: 31,
        uploaded_at: "2026-07-21T15:02:00Z",
        uploaded_by_stakeholder_id: "s3",
      },
    ],
    ai_review: {
      id: "air_070",
      evidence_file_id: "f_070",
      model: "gpt-4.1",
      reviewed_at: "2026-07-21T15:04:00Z",
      doc_type: "HR Offboarding Checklist",
      doc_type_alternatives: ["Termination Record"],
      summary:
        "31 pages containing 14 completed offboarding checklists. Each lists termination date, manager sign-off, and a systems-access removal section. 3 checklists have the access removal section blank.",
      completeness: "partial",
      suggested_control_refs: ["CC6.3", "CC1.4"],
      flags: [
        {
          id: "fl_6",
          severity: "blocker",
          title: "3 checklists missing access removal confirmation",
          detail: "Pages 9, 17, and 24 have an empty 'Systems access revoked (date/by)' field.",
          location: "pp. 9, 17, 24",
        },
      ],
      excerpts: [
        { location: "p.17", text: "Systems access revoked (date / by): ______________" },
      ],
    },
    decision: {
      id: "dec_070",
      decision: "request_more",
      note: "Please supply the completed access-removal section for the three leavers on pp. 9, 17 and 24, or the corresponding IdP deprovisioning logs.",
      decided_by: "A. Rao",
      decided_at: "2026-07-26T09:12:00Z",
    },
  },
  {
    id: "req_003",
    engagement_id: "eng_001",
    control_ref: "CC6.1",
    title: "MFA enforcement configuration: identity provider",
    description: "Screenshot or config export showing MFA enforced for all users on the corporate IdP.",
    stakeholder_id: "s4",
    status: "approved",
    due_date: "2026-07-15",
    sent_at: "2026-07-02T10:00:00Z",
    reminder_count: 0,
    last_activity_at: "2026-07-14T13:30:00Z",
    files: [
      {
        id: "f_030",
        filename: "idp-mfa-policy-export.pdf",
        mime_type: "application/pdf",
        size_bytes: 96_200,
        page_count: 2,
        uploaded_at: "2026-07-12T08:44:00Z",
        uploaded_by_stakeholder_id: "s4",
      },
    ],
    ai_review: {
      id: "air_030",
      evidence_file_id: "f_030",
      model: "gpt-4.1",
      reviewed_at: "2026-07-12T08:46:00Z",
      doc_type: "IdP Configuration Export",
      doc_type_alternatives: ["Security Policy Screenshot"],
      summary:
        "Two-page policy export dated 12 Jul 2026 showing a conditional access policy 'Require MFA (All Users)' in Enabled state, scoped to all users with no exclusion groups.",
      completeness: "complete",
      suggested_control_refs: ["CC6.1"],
      flags: [],
      excerpts: [
        { location: "p.1", text: "Policy: Require MFA (All Users) | State: Enabled | Excluded groups: none" },
      ],
    },
    decision: {
      id: "dec_030",
      decision: "approve",
      note: "Config export is point-in-time as of 12 Jul. Accepted alongside the sampled sign-in logs under REQ-004.",
      decided_by: "A. Rao",
      decided_at: "2026-07-14T13:30:00Z",
    },
  },
  {
    id: "req_012",
    engagement_id: "eng_001",
    control_ref: "A1.2",
    title: "Backup restoration test results",
    description: "Evidence of at least one successful restoration test performed during the period.",
    stakeholder_id: "s2",
    status: "ai_processing",
    due_date: "2026-08-04",
    sent_at: "2026-07-20T11:00:00Z",
    reminder_count: 0,
    last_activity_at: "2026-07-29T08:52:00Z",
    files: [
      {
        id: "f_120",
        filename: "restore-test-2026-05.pdf",
        mime_type: "application/pdf",
        size_bytes: 305_900,
        page_count: 4,
        uploaded_at: "2026-07-29T08:51:00Z",
        uploaded_by_stakeholder_id: "s2",
      },
    ],
    ai_review: null,
    decision: null,
  },
  {
    id: "req_009",
    engagement_id: "eng_001",
    control_ref: "CC7.2",
    title: "Security monitoring alert log: sample of 20 alerts",
    description: "Alert records showing detection, triage, and resolution for a sample of 20 alerts.",
    stakeholder_id: "s4",
    status: "awaiting_upload",
    due_date: "2026-07-22",
    sent_at: "2026-07-08T10:30:00Z",
    reminder_count: 3,
    last_activity_at: "2026-07-28T06:00:00Z",
    files: [],
    ai_review: null,
    decision: null,
  },
  {
    id: "req_010",
    engagement_id: "eng_001",
    control_ref: "CC7.3",
    title: "Incident post-mortems for the period",
    description: "Post-incident reviews for all severity 1 and 2 incidents during the period.",
    stakeholder_id: "s4",
    status: "awaiting_upload",
    due_date: "2026-07-26",
    sent_at: "2026-07-13T09:15:00Z",
    reminder_count: 1,
    last_activity_at: "2026-07-27T06:00:00Z",
    files: [],
    ai_review: null,
    decision: null,
  },
  {
    id: "req_013",
    engagement_id: "eng_001",
    control_ref: "CC9.2",
    title: "Vendor risk assessments: critical vendors",
    description: "Most recent risk assessment and SOC 2 report review for each critical vendor.",
    stakeholder_id: "s5",
    status: "awaiting_upload",
    due_date: "2026-08-07",
    sent_at: "2026-07-22T14:00:00Z",
    reminder_count: 0,
    last_activity_at: "2026-07-22T14:00:00Z",
    files: [],
    ai_review: null,
    decision: null,
  },
  {
    id: "req_015",
    engagement_id: "eng_001",
    control_ref: "CC1.4",
    title: "Security awareness training completion records",
    description: "Completion report for annual security awareness training covering all employees.",
    stakeholder_id: "s3",
    status: "awaiting_upload",
    due_date: "2026-08-11",
    sent_at: "2026-07-24T09:00:00Z",
    reminder_count: 0,
    last_activity_at: "2026-07-24T09:00:00Z",
    files: [],
    ai_review: null,
    decision: null,
  },
  {
    id: "req_016",
    engagement_id: "eng_001",
    control_ref: "CC2.2",
    title: "Internal security policy acknowledgements",
    description: "Records showing employees acknowledged the information security policy.",
    stakeholder_id: "s3",
    status: "not_sent",
    due_date: "2026-08-14",
    sent_at: null,
    reminder_count: 0,
    last_activity_at: "2026-07-25T17:10:00Z",
    files: [],
    ai_review: null,
    decision: null,
  },
  {
    id: "req_008",
    engagement_id: "eng_001",
    control_ref: "CC6.1",
    title: "Firewall rule set export: production VPC",
    description: "Current security group and network ACL configuration for production.",
    stakeholder_id: "s2",
    status: "rejected",
    due_date: "2026-07-20",
    sent_at: "2026-07-06T10:00:00Z",
    reminder_count: 1,
    last_activity_at: "2026-07-23T14:05:00Z",
    files: [
      {
        id: "f_080",
        filename: "sg-rules-screenshot.png",
        mime_type: "image/png",
        size_bytes: 1_120_000,
        page_count: null,
        uploaded_at: "2026-07-22T19:30:00Z",
        uploaded_by_stakeholder_id: "s2",
      },
    ],
    ai_review: {
      id: "air_080",
      evidence_file_id: "f_080",
      model: "gpt-4.1",
      reviewed_at: "2026-07-22T19:32:00Z",
      doc_type: "Configuration Screenshot",
      doc_type_alternatives: ["Firewall Rule Export"],
      summary:
        "A single screenshot of an AWS console security group listing. No timestamp, account identifier, or environment label is visible, and the list is visibly truncated at the bottom of the frame.",
      completeness: "insufficient",
      suggested_control_refs: ["CC6.1"],
      flags: [
        {
          id: "fl_7",
          severity: "blocker",
          title: "No date or system context visible",
          detail: "Screenshot lacks a timestamp and account/environment identifier, so it cannot be tied to the audit period or to production.",
          location: "Whole image",
        },
        {
          id: "fl_8",
          severity: "blocker",
          title: "Content truncated",
          detail: "The rule list is cut off at the frame edge; an unknown number of rules are not shown.",
          location: "Whole image",
        },
      ],
      excerpts: [],
    },
    decision: {
      id: "dec_080",
      decision: "reject",
      note: "Screenshots aren't sufficient for this control. Please provide a CLI export (describe-security-groups) with the account ID and export timestamp included.",
      decided_by: "A. Rao",
      decided_at: "2026-07-23T14:05:00Z",
    },
  },
  {
    id: "req_004",
    engagement_id: "eng_001",
    control_ref: "CC6.1",
    title: "Sign-in logs: sample of 30 privileged sessions",
    description: "Authentication logs evidencing MFA challenge for privileged accounts.",
    stakeholder_id: "s4",
    status: "approved",
    due_date: "2026-07-15",
    sent_at: "2026-07-02T10:00:00Z",
    reminder_count: 0,
    last_activity_at: "2026-07-14T13:31:00Z",
    files: [
      {
        id: "f_040",
        filename: "privileged-signin-sample.csv",
        mime_type: "text/csv",
        size_bytes: 51_200,
        page_count: null,
        uploaded_at: "2026-07-11T12:10:00Z",
        uploaded_by_stakeholder_id: "s4",
      },
    ],
    ai_review: {
      id: "air_040",
      evidence_file_id: "f_040",
      model: "gpt-4.1",
      reviewed_at: "2026-07-11T12:12:00Z",
      doc_type: "Authentication Log Export",
      doc_type_alternatives: [],
      summary:
        "CSV of 30 privileged sign-in events sampled across the period. All 30 rows show mfa_satisfied = true with a matching authentication method.",
      completeness: "complete",
      suggested_control_refs: ["CC6.1"],
      flags: [],
      excerpts: [],
    },
    decision: {
      id: "dec_040",
      decision: "approve",
      note: "Sample agrees to the population export. No exceptions.",
      decided_by: "A. Rao",
      decided_at: "2026-07-14T13:31:00Z",
    },
  },
];

/** Activity log for the drill-in screen. In production this is one query on activity_log. */
export const activityLog: ActivityEntry[] = [
  {
    id: "a1",
    request_id: "req_014",
    actor: "A. Rao",
    actor_type: "auditor",
    action: "Request created",
    detail: "Assigned to Marcus Webb (IT Manager), due 24 Jul 2026",
    created_at: "2026-07-10T14:00:00Z",
  },
  {
    id: "a2",
    request_id: "req_014",
    actor: "System",
    actor_type: "system",
    action: "Evidence request emailed",
    detail: "Secure upload link sent to m.webb@northwind.example",
    created_at: "2026-07-10T14:02:00Z",
  },
  {
    id: "a3",
    request_id: "req_014",
    actor: "System",
    actor_type: "system",
    action: "Reminder sent",
    detail: "Automated reminder: 2 days before due date",
    created_at: "2026-07-22T06:00:00Z",
  },
  {
    id: "a4",
    request_id: "req_014",
    actor: "Marcus Webb",
    actor_type: "stakeholder",
    action: "File uploaded",
    detail: "Q2-2026-AWS-access-review.pdf (403 KB)",
    created_at: "2026-07-28T16:38:00Z",
  },
  {
    id: "a5",
    request_id: "req_014",
    actor: "Marcus Webb",
    actor_type: "stakeholder",
    action: "File uploaded",
    detail: "iam-users-export-2026-06-30.csv (86 KB)",
    created_at: "2026-07-28T16:40:00Z",
  },
  {
    id: "a6",
    request_id: "req_014",
    actor: "AI review",
    actor_type: "ai",
    action: "Analysis completed",
    detail: "Classified as Access Review Export, completeness: partial, 4 flags raised",
    created_at: "2026-07-28T16:41:00Z",
  },
];

export function getRequest(id: string): EvidenceRequest | undefined {
  return evidenceRequests.find((r) => r.id === id);
}

export function getActivityFor(requestId: string): ActivityEntry[] {
  return activityLog
    .filter((a) => a.request_id === requestId)
    .sort((a, b) => b.created_at.localeCompare(a.created_at));
}
